version: "3.2"
services:
  qrcode-flask:
    build: .
    ports:
      - 80:8080
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      QR_CODE_FILE_NAME: 'qrcode.png'
      QR_CODE_FILE_PATH: 'images'
      QR_CODE_DATA: 'https://hub.docker.com/repository/docker/charanravela54/qrcode'
    volumes:
      - .:/home/flaskscript
  ubuntu:
    image: kaw393939/myubuntimage
    stdin_open: true # docker run -i
    tty: true        # docker run -t
